team_realms:
  - realm_name: "team1"
    display_name: "Team 1"

    clients:
      - name: "application1"
        client_id: "d8503df2-941c-461f-be30-7c550f688bea"

        scopes_as_array: true

        redirect_uris:
          - "https://my_app.apps.example.com/*"

        web_origins:
          - "https://my_app.apps.example.com"

        roles:
          - name: "admin"
            scope: "application.admin"
            scope_default: false
            external_group: "EXTERNAL_GROUP_application-ADMIN"
            external_group_sync_mode: "INHERIT"
          - name: "ecriture"
            scope: "application.ecriture"
            scope_default: false
            external_group: "EXTERNAL_GROUP-application-ECRITURE"
            external_group_sync_mode: "INHERIT"
          - name: "lecture"
            scope: "application.lecture"
            scope_default: false
            external_group: "EXTERNAL_GROUP-application-LECTURE"
            external_group_sync_mode: "INHERIT"

    extra_group_mappers:
      - external_group: "SR-PaaS-Operateurs-N2"
        role: "realm-management.realm-admin"
        sync_mode: "INHERIT"

  - realm_name: "team2"
    display_name: "Team 2"
